### ISSUE TITLE
Kanboard Plugin Page Pulls Outdated Plugin Version

### ISSUE THREAD

**Issue by Snuupy** [ptr0x01/kanboard-plugin-zulip#4]
Edit 2: this is because the version pulled from Kanboard's plugin page is outdated. The maintainer will either need to update that package (to master) or users can clone the repo from master and use that. The version in the Kanboard repo also doesn't support private messages.

Edit 1:

Turns out my install was missing

```php
use Kanboard\Model\TaskModel;
```

in `plugins/Zulip/Notification/Zulip.php` for some strange reason.

Hi, I believe this plugin is broken on latest kanboard. Can you reproduce?

I've attached the log below:

```
kanboard      | PHP message: PHP Fatal error:  Uncaught Error: Class 'Kanboard\Plugin\Zulip\Notification\TaskModel' not found in /var/www/app/plugins/Zulip/Notification/Zulip.php:31"
kanboard      | Stack trace:"
kanboard      | #0 /var/www/app/app/Model/UserNotificationModel.php(54): Kanboard\Plugin\Zulip\Notification\Zulip->notifyUser(Array, 'comment.create', Array)"
kanboard      | #1 /var/www/app/app/Model/UserNotificationModel.php(29): Kanboard\Model\UserNotificationModel->sendUserNotification(Array, 'comment.create', Array)"
kanboard      | #2 /var/www/app/app/Job/NotificationJob.php(39): Kanboard\Model\UserNotificationModel->sendNotifications('comment.create', Array)"
kanboard      | #3 [internal function]: Kanboard\Job\NotificationJob->execute(Array, 'comment.create')"
kanboard      | #4 /var/www/app/app/Core/Queue/QueueManager.php(52): call_user_func_array(Array, Array)"
kanboard      | #5 /var/www/app/app/Subscriber/NotificationSubscriber.php(45): Kanboard\Core\Queue\QueueManager->push(Object(Kanboard\Job\NotificationJob))"
kanboard      | #6 /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Kanboard\Subscriber\Notification..."
kanboard      | 2020/09/13 13:53:55 [error] 14#14: *79 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Kanboard\Plugin\Zulip\Notification\TaskModel' not found in /var/www/app/plugins/Zulip/Notification/Zulip.php:31
kanboard      | Stack trace:
kanboard      | #0 /var/www/app/app/Model/UserNotificationModel.php(54): Kanboard\Plugin\Zulip\Notification\Zulip->notifyUser(Array, 'comment.create', Array)
kanboard      | #1 /var/www/app/app/Model/UserNotificationModel.php(29): Kanboard\Model\UserNotificationModel->sendUserNotification(Array, 'comment.create', Array)
kanboard      | #2 /var/www/app/app/Job/NotificationJob.php(39): Kanboard\Model\UserNotificationModel->sendNotifications('comment.create', Array)
kanboard      | #3 [internal function]: Kanboard\Job\NotificationJob->execute(Array, 'comment.create')
kanboard      | #4 /var/www/app/app/Core/Queue/QueueManager.php(52): call_user_func_array(Array, Array)
kanboard      | #5 /var/www/app/app/Subscriber/NotificationSubscriber.php(45): Kanboard\Core\Queue\QueueManager->push(Object(Kanboard\Job\NotificationJob))
kanboard      | #6 /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Kanboard\Subscriber\Notification" while reading response header from upstream, client: 172.28.0.1, server: localhost, request: "POST /?controller=CommentController&action=save&task_id=83&project_id=5 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "kanboard.domain.tld"
```

Application stack:

Application version: v1.2.15
PHP version: 7.3.19
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.4.0-42-generic
Database driver: postgres
Database version: 12.3

**Comment by ptr0x1** [comment]
Thanks for this I'll look at it and update it when I have some time.

**Comment by Snuupy** [comment]
@ptr0x1 I fixed it, just give me a day or so to submit a PR )
